- setup.py
- tests/fixture.csv
- tests/test_storage.py
- treehouse/messaging.py
- treehouse/storage.py
see https://reclabs.atlassian.net/browse/DATA-90
> Replaced CSV processing with less memory intensive solution

- treehouse/storage.py
due to the nature of how CSV is processed now (agnostically), we can't make any choices on what type conversions should be done
according to google this is the way how to do that https://stackoverflow.com/a/37715134
> Prevent any type conversions

- terraform/cloud_function/pubsub_triggered/main.tf
- terraform/cloud_function/pubsub_triggered/variables.tf
Moved from data-ingestors here to make it reusable for other repos
Also added a few more optional variables to allow for different runtimes and entry_points
> Added pubsub function resources

- terraform/cloud_function/scheduled/main.tf
- terraform/cloud_function/scheduled/outputs.tf
- terraform/cloud_function/scheduled/variables.tf
Moved from ingestors to here for reusability
Also added a few more optional variables to allow for different runtimes and entry_points
> Added scheduled cloud function module

- terraform/cloud_function/pubsub_triggered/main.tf
- terraform/cloud_function/scheduled/main.tf
Reverts Pararius/platform-tools#31
> Revert "Use managed zip"

- setup.py
- treehouse/dates.py
- treehouse/db.py
Also some date helpers that are often used (mostly to reduce number of times we define the date format)
> Added postgres functionality

- treehouse/db.py
Also return number of records that were eventually processed
> Allow skipping of empty df's

- treehouse/datetime.py
Made fallback function less strict and added docs.  Also moved to more generic `datetime` module
> Refactored date stuff

- Dockerfile
- Makefile
- tests/test_storage.py
- treehouse/storage.py
fyi; double-checked our other repos to make sure none were assuming client is third argument
> Added support for columns to parquet reads

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- requirements.txt
- treehouse/pyspark.py
Adds a CD pipeline to deploy a zipfile of the platform-tools Python package (treehouse) with all dependencies
> Deploy pftools artifact

- terraform/cloud_function/scheduled/variables.tf
- terraform/main.tf
needed to work with the terraform apply action created by devops, following https://www.terraform.io/language/upgrade-guides#concluding-the-optional-attributes-experiment
> Disabled experiment

- treehouse/pyspark.py
Might as well move this function to platform-tools so we can reuse it later
Moved function from curators to here
https://reclabs.atlassian.net/browse/DATA-698
see related PR https://github.com/Pararius/data-curators/pull/249
> Added safe_col function

- treehouse/pyspark.py
Forgot to add an import for the exception handling
Added import
none
> Fixed missing import

- treehouse/db.py
- treehouse/messaging.py
- treehouse/utils.py
AKA 'ingestionbuffer', a lot of functions have become redundant by now so this PR became a lot smaller
Mainly adds a function to calculate timezones from an interval string, and automatically closing the connection after opening it in the `query_to_df` function
> Tweaks after initial boilerplate

- terraform/main.tf
- terraform/routines.tf
- terraform/woothee.js
Make the user agent parser routine generally available outside the `dm_search`
Stick it in the `fn` dataset.
*If there is a JIRA issue related to this change, add a link to it here*
> add user agent parser routine

- terraform/routines.tf
Less typing
Use stored routines instead of typing.
*If there is a JIRA issue related to this change, add a link to it here*
> add routines for getting json values

- terraform/bigquery_scheduled_data_transfer/README.md
- terraform/bigquery_scheduled_data_transfer/main.tf
- terraform/bigquery_scheduled_data_transfer/variables.tf
- tests/test_storage.py
*Please explain the problem you are trying to fix in a few sentences, providing enough context so anyone in our team can understand it.*
*Describe how this PR will fix the problem mentioned above. This is used by reviewers to determine if the correct solution was chosen and was implemented correctly*
*If there is a JIRA issue related to this change, add a link to it here*
> add BQ data transfer module

- terraform/routines.tf
Need to handle more cases than I initially thought
Added more cases
n/a
> Added more emptyish cases

- terraform/routines.tf
*Please explain the problem you are trying to fix in a few sentences, providing enough context so anyone in our team can understand it.*
*Describe how this PR will fix the problem mentioned above. This is used by reviewers to determine if the correct solution was chosen and was implemented correctly*
*If there is a JIRA issue related to this change, add a link to it here*
> add routine to parse dutch dates

- treehouse/pyspark.py
- treehouse/utils.py
Noticed that our daily scheduling is sensitive to shifting starting hours.
Decided to force the hour to 0 so the slice is always consistent and without gaps.
n/a
> Use 0th hour for daily intervals

- Makefile
- compose.yaml
- docker-compose.yaml
- docker/cs/Dockerfile
- terraform/bigquery_scheduled_data_transfer/main.tf
- terraform/bigquery_scheduled_data_transfer/variables.tf
- terraform/cloud_function/pubsub_triggered/main.tf
- terraform/cloud_function/pubsub_triggered/variables.tf
- terraform/cloud_function/scheduled/main.tf
- terraform/cloud_function/scheduled/variables.tf
- terraform/routines.tf
- terraform/storage/main.tf
- terraform/storage/variables.tf
First part of getting better insights into our costs, is labeling our resources. However, some of our terraform projects use modules from this platform-tools repo, so we need to add support for labels to the underlying resources first.
Made labels configurable for all modules
https://reclabs.atlassian.net/browse/DATA-1358
> Add support for labeling resources
